### ISSUE TITLE
Getting errors when setting up latest version of Resume Parser?

### ISSUE THREAD

**Issue by Shrinidhikulkarni7** [bjherger/ResumeParser#15]
I have install anaconda and when i want to create  the environment from the environment.yml file
I type -conda env create -f environment.yml
And get this error-
resolve package not found -openssl 1.0.2h 2 conda.

By the way you guys have done a great job, Thank you :)

**Comment by bjherger** [comment]
Hey,

What’s your OS and python version?

Also, mostly just me, but thanks!
BH

**Comment by Shrinidhikulkarni7** [comment]
@bjherger 
OS- Windows 7
Python- 2.7.
Yeah, you have done a great job :)

**Comment by daraed95** [comment]
I am experiencing the same issue as @Shrinidhikulkarni7 
I am running Windows 7 and Python 3.6.3

**Comment by bjherger** [comment]
@Shrinidhikulkarni7 @bmcnitt : The version of `openssl` listed appears to be specific to MacOS. I've removed the `openssl` requirement, though anaconda will still install the correct version of `openssl` for your system (it is a requirement for other packages). Please confirm that this fix works for you.

**Comment by bmcnitt** [comment]
@bjherger 

Appreciate the help.
This is what returns when I run -conda env create -f environment.ym


Using Anaconda API: https://api.anaconda.org
Fetching package metadata ...........

NoPackagesFoundError: Package missing in current win-64 channels:
  - python 2.7.12 1

**Comment by daraed95** [comment]
@bjherger Appreciate the help. I a beginner at python..

It looks like I am having trouble with the dependencies in the .yml file. How would I go about fixing the problem of the terminal returning:

ResolvePackageNotFound
 
I did not get the error for pip 8.1.2, but I did for python 2.7.12. I tried installing this version of python and it did not resolve the issue. I removed this line and also got the error for readlines 6.2.

**Comment by bjherger** [comment]
@bmcnitt : Are you using anaconda to create the environment, as described in the README?

**Comment by daraed95** [comment]
@bjherger Yes I am using the anaconda command prompt

**Comment by bjherger** [comment]
@bmcnitt : Could you send the command you're running, and the entire output?

**Comment by daraed95** [comment]
@bjherger 
[resumeparser problem.pdf](https://github.com/bjherger/ResumeParser/files/1442748/resumeparser.problem.pdf)

**Comment by karang8** [comment]
@bjherger I'm having the same issue as @bmcnitt . Please see if there is a fix.

**Comment by antu12** [comment]
dependencies:
- !!python/unicode 
  'pip=8.1.2=py27_0'  **(Worked)**
- !!python/unicode  
  'python=2.7.12=0' **(ERROR: ResolvePackageNotFound)**
- !!python/unicode 
  'readline=6.2=2' **(ERROR: ResolvePackageNotFound)**
- !!python/unicode 
  'setuptools=26.1.1=py27_0' **(Worked)**
- !!python/unicode
  'sqlite=3.13.0=0' **(ERROR: ResolvePackageNotFound)**
- !!python/unicode
  'tk=8.5.18=0' **(ERROR: ResolvePackageNotFound)**
- !!python/unicode
  'wheel=0.29.0=py27_0' **(ERROR: ResolvePackageNotFound)**
- !!python/unicode
  'zlib=1.2.8=3' **(ERROR: ResolvePackageNotFound)**

N.B: I'm on windows 7 and changed my anaconda to install python 2.7.12

**Comment by bjherger** [comment]
I believe these issues are stemming from using the Python 3.X version of Anaconda, rather than the  2.7 version of Anaconda. I've updated the `README` to specify that the Python 2.7 version of Anaconda is required.

If any of you continue to have this issue, while using the Python 2.7 version of Anaconda, please re-open this issue and respond with your command and output, similar to @bmcnitt .

**Comment by camoore2** [comment]
I'm having the same issue on Widows 7, python 2.7 in a 32 bit environment.  

(py27_32) C:\Users\camoore\Documents\GitHub\ResumeParser>conda env create -f env
ironment.yml
Solving environment: failed

ResolvePackageNotFound:
  - sqlite==3.13.0=0
  - zlib==1.2.8=3
  - tk==8.5.18=0
  - readline==6.2=2

I'm not sure how to interpret the environment.yml file.  Like if there are different packages for Windows vs. Mac.

I was able to get all sqlite, zlib, tk from a conda install, but still get an issue with dependencies.
Can't seem to find readline

**Comment by bjherger** [comment]
@camoore2 I believe the version numbers for those packages can be safely ignored. If you can create a pull request for those packages without specific versions, I’d be happy to merge it. Otherwise, it might take me a few days to make these updates.

**Comment by camoore2** [comment]
I removed the version references and that worked, renamed readline to pyreadline (I'm still installing so we'll see if that works.)  If I'm successful, I create the pull request and make the updates.

**Comment by camoore2** [comment]
Ok, it worked.  
- I forced the 32 bit anaconda for 2.7 so textract would install.
- Removed the version numbers for the above packages

I will be extending to find dates and titles, but this is a HUGE help to start.  Thank you.

**Comment by ShimiraSenarath** [comment]
I'm using windows 10
python 2.7
I got this error
![error](https://user-images.githubusercontent.com/29924958/42927233-76af022a-8b51-11e8-8b08-daf35b937bfc.png)
