### ISSUE TITLE
[Feature Request] Can you provide API calls?

### ISSUE THREAD

**Issue by Shrinidhikulkarni7** [bjherger/ResumeParser#16]
Hey @bjherger , I have been using your old Resume Parser itself(previous version). 
Can you help me by providing REST API calls?

**Comment by bjherger** [comment]
@Shrinidhikulkarni7 : Thanks for reaching out. Providing a RESTful service / API would require something like:

 - Setting up a server (such [Flask](http://flask.pocoo.org/))
 - Setting it up to receive files
 - Setting it up to send back appropriately formatted responses
Unfortunately, this is out of scope for this project. If you'd like to set up a sister project that sets up this RESTful service, I'd be happy to collaborate on it.

**Comment by bjherger** [comment]
Issue out of scope. Closing.
