### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by iwangu** [bjherger/ResumeParser#17]

**Comment by bjherger** [comment]
Not at this time. I’d be happy to review a PR that adds Python 3 support,
but I do not have the bandwidth to add it myself.

**Comment by Shrinidhikulkarni7** [comment]
@iwangu You can always do this-
from __future__ import print_function, division, absolute_imports, unicode_literals

**Comment by akashpandey111** [comment]
@bjherger I could do that

**Comment by bjherger** [comment]
@akashpandey111 This app should mostly be Python 3 comparable, except for the following known issues

 - Python 2 style `print` statements
 - No `environment.yml` file for Python 3 version of packages. 
 - No instructions in `README` for using Python 3 version of `environment.yml`

If you'd like to remedy these issues, test that everything works, and submit a PR, I'd appreciate the help.

**Comment by charl4e** [comment]
I'm currently running this app on Python3, had very few issues with installing. Only issue I currently have is the app is not picking up new skills added to the config.yaml file, not sure if it's related to Python3 though..
