### ISSUE TITLE
Textract Dependency Issues

### ISSUE THREAD

**Issue by soppliger** [bjherger/ResumeParser#18]
I installed Anaconda and followed the install instructions to the letter. When I run `python main.py` I get the following error:

```
File "/Users/Scott/anaconda2/envs/resume/lib/python2.7/site-packages/textract/parsers/utils.py", line 101, in run
    ' '.join(args), pipe.returncode, stdout, stderr,
textract.exceptions.ShellError: The command `pdf2txt.py ../data/input/example_resumes/Brendan_Herger_Resume.pdf` failed because the executable
`pdf2txt.py` is not installed on your system.
```

pdf2txt is a dependency of textract, but I notice that it's commented out of the requirements.txt in 1.6.1. I tried to manually install it, but it didn't resolve the issue.

**Comment by bjherger** [comment]
@soppliger : Thanks for your input. I believe you're using an older or non-master version of the app. Installation through `pip` with the `requirements.txt` file is no longer supported. If you're still having this issue, please use the `environment.yml` file, as described in the `README`. If you're still having this issues, please re-open this issue, or open a new issue.
