### ISSUE TITLE
can't find model 'en'

### ISSUE THREAD

**Issue by AdamLouly** [bjherger/ResumeParser#36]
getting this error when launching main.py
guess something in confs?
IOError: [E050] Can't find model 'en'. It doesn't seem to be a shortcut link, a Python package or a valid path to a data directory.

**Comment by AshishDhadwal** [comment]
Install spacy by running anaconda prompt in admin mode.
pip install -U spacy 
python -m spacy download en.

**Comment by AdamLouly** [comment]
![image](https://user-images.githubusercontent.com/27873459/55331877-1f5f3a80-548c-11e9-8349-1ff497afde24.png)

**Comment by AshishDhadwal** [comment]
pip install ujson

**Comment by bjherger** [comment]
@AdamLouly Are you still hitting issues?
