### ISSUE TITLE
Syntax error with Resumechecker.py

### ISSUE THREAD

**Issue by poornagurram** [bjherger/ResumeParser#5]
![screenshot from 2017-04-07 19-15-11](https://cloud.githubusercontent.com/assets/9065157/24802762/c1619554-1bc6-11e7-8911-6a36acc099b7.png)

**Comment by bjherger** [comment]
Hey,

Python 3 is not supported at this time. I only have time to test with /
support one python version, and I've gone with python 2.7.

**Comment by poornagurram** [comment]
But it's the same with python 2.7 too.could please check what's the problem.
![screenshot from 2017-04-08 10-26-18](https://cloud.githubusercontent.com/assets/9065157/24825849/dc227b72-1c45-11e7-8a4e-59a3f40b1958.png)

**Comment by poornagurram** [comment]
When I'm trying with" sudo python filename.py" it's coming..May I know what might be the problem ??

**Comment by bjherger** [comment]
Hey, it looks like this occurring because you're default python installation is also python 3.x. Please try calling `python2 ResumeChecker.py`, or equivalent.

**Comment by bjherger** [comment]
Closing, issue (supporting python 3.x) is out of scope.
