### ISSUE TITLE
what's the cons/pros compare with another tool antonydeepak/ResumeParser?

### ISSUE THREAD

**Issue by hbakhtiyor** [bjherger/ResumeParser#7]
https://github.com/antonydeepak/ResumeParser

**Comment by Shrinidhikulkarni7** [comment]
The parser which you mentioned is not able to fetch the name properly.

**Comment by bjherger** [comment]
@hbakhtiyor : If another tool meets you needs, please use it. 

Additionally, this doesn't seem to be an issue, so much as an advertisement for another project. I'm closing this issue as it does not:

 - Identify a bug
 - Identify a feature request
 - Request a modification of the codebase

If your request falls into one of the above categories, please submit another issue, and I'd be happy to work on it.
